
window.movies = [
    'grease',
    'Titanic',
    'Harry Potter',
    'Star Wars',
    'Spider-Man',
    'Shrek',
    'Buscando a Nemo',
    'Independence Day',
    'El rey león',
    'El código Da Vinci',
    'E.T.: El extraterrestre',
    'Las Crónicas de Narnia',
    'Matrix',
    'El sexto sentido',
    'Los increíbles',
    'La Pasión de Cristo',
    'La Guerra de los Mundos',
    '007 Casino Royale',
    'Men in Black',
    'Noche en el museo',
    'Armageddon',
    'King Kong',
    'Misión Imposible',
    'Transformers',
    'Solo en casa',
    'Monstruos, S.A.',
    'El día de mañana',
    'Ghost',
    'Terminator',
    'Aladdin',
    'Indiana Jones',
    'Toy Story',
    'Troya',
    'Salvad al soldado Ryan',
    'Charlie y la fábrica de chocolate',
    'Tiburón',
    'Pretty Woman',
    'Como Dios',
    'Gladiator',
    'X-Men',
    'Cars',
    '300',
    'Pearl Harbor',
    'Ocean’s Eleven',
    'El último Samurai',
    'Tarzán',
    'Los padres de él',
    'Sr.y Sra.Smith',
    'Men in Black',
    'Naúfrago',
    'Sra.Doubtfire',
    'La momia',
    'Batman',
    'Rain Man',
    'El guardaespaldas',
    'Señales',
    'Madagascar',
    'Lo que el viento se llevó',
    'Robin Hood',
    'Superman',
    'Grease',
    'Happy Feet',
    'La Bella y la Bestia',
    'Ice Age',
    'Godzilla',
    '¿En qué piensan las mujeres?',
    'El fugitivo',
    'Hitch',
    'Jungla de cristal',
    'Notting Hill',
    'Algo pasa con Mary',
    'El planeta de los simios',
    'Los picapiedra',
    'Toy Story',
    'Minority Report',
    'Bichos',
    'El exorcista',
    'Mi gran boda griega',
    'Instinto Básico',
    'Regreso al futuro',
    'Se7en',
    '¿Quién engaño a Rogger Rabbit?',
    'Hannibal',
    'Pocahontas',
    'Ratatouille',
    'Yo, Robot',
    'El Grinch',
    'Atrápame si puedes',
    'American Beauty',
    'Los 4 fantásticos',
    'Hora punta',
    'Crocodilo Dundee',
    'El jorobado de Notre Dame',
    'El diablo viste de Prada',
    'La lista de Schindler',
    'La máscara',
    'Arma letal',
    'Superdetective en Hollywood',
    'Mejor imposible',
    'Una mente maravillosa',
    'Austin Powers',
    'Novia a la fuga',
    'Chicago',
    'Mentiroso compulsivo',
    'El espantatiburones',
    '101 Dálmatas',
    'Mulan',
    'Hook',
    'Rocky',
    'Rambo',
    'Chicken Little',
    'En busca de la felicidad',
    'Stuart Little',
    'Mira quien habla',
    'Los padres de ella',
    'Los cazafantasmas',
    'Doctor Dolittle',
    'Shakespeare',
    'El príncipe de Zamunda',
    'Speed',
    'Casper',
    'Infiltrados',
    'Lo que la verdad esconde',
    'El silencio de los corderos',
    'El profesor chiflado',
    'La milla verde',
    'Bambi',
    'XXX',
    'Jumanji',
    'El quinto elemento',
    'Lilo & Stitch',
    'Desafío total',
    'Borat',
    'Scary Movie',
    'Los ángeles de Charlie',
    'Full Monty',
    'El diario de Bridget Jones',
    'Los ángeles de Charlie',
    'Lara Croft',
    'Hércules',
    'El show de Truman',
    'Babe',
    'El protegido',
    'Dos tontos muy tontos',
    'Robots',
    'Hora punta',
    'Enemigo público',
    'El padrino',
    'Cuatro bodas y un funeral',
    '8 Millas',
    'Hulk',
    'Memorias de África',
    'Love Actually',
    'Fiebre del sábado noche',
    'Fast and Furious',
    'Un papá genial',
    'Las máscara del Zorro',
    'Bean',
    'El paciente inglés',
    'The Ring',
    'Inteligencia Artificial',
    'Constantine',
    'La vida es bella',
    'Hermano oso',
    'Space Jam',
    '101 Dálmatas',
    'Cariño, he encogido a los niños',
    'La Sirenita',
    'Ghost Rider',
    'El príncipe de Egipto',
    'La Terminal',
    'Wild Wild West',

    'El patriota',
    'El caso Bourne',
    'Pulp Fiction',
    'Ace Ventura',
    'Los otros',
    'Miss Agente especial',
    'El libro de la selva',
    'Braveheart',
    'Las tortugas ninja',
    'American Pie',
    "Titanic", "Piratas del caribe", "Avatar", "Forrest gum", "El señor de los anillos", "Parque jurasico", "Gladiator", "Ironman", "El exorcista", "Batman el caballero oscuro", "Saw", "King Kong", "El padrino", "Terminator", "El sexto sentido", "Pretty woman", "Matrix", "La lista de Schindlerss", "Braveheart", "Pesadilla en Elm Street", "Cadena perpetua", "Dia de la independencia", "El silencio de los corderos", "Psicosis", "Terminator", "El resplandor", "Pulp fiction", "Los otros", "Bailando con lobos", "Jungla de cristal", "6 balas", "Sin perdon",
];

