
window.movies = [
    'Titanic',
    'Harry Potter',
    'Star Wars',
    'Spider-Man',
    'Shrek',
    'Buscando a Nemo',
    'El rey león',
    'El código Da Vinci',
    'E.T.: El extraterrestre',
    'Las Crónicas de Narnia',
    'Matrix',
    'El sexto sentido',
    'Los increíbles',
    'La Pasión de Cristo',
    'La Guerra de los Mundos',
    '007 Casino Royale',
    'Men in Black',
    'Noche en el museo',
    'Armageddon',
    'King Kong',
    'Misión Imposible',
    'Transformers',
    'Solo en casa',
    'Monstruos, S.A.',
    'El día de mañana',
    'Ghost',
    'Terminator',
    'Aladdin',
    'Indiana Jones',
    'Toy Story',
    'Troya',
    'Salvar al soldado Ryan',
    'Charlie y la fábrica de chocolate',
    'Tiburón',
    'Como Dios',
    'Gladiator',
    'X-Men',
    'Cars',
    '300',
    'Pearl Harbor',
    'Ocean\'s Eleven',
    'El último Samurai',
    'Tarzán',
    'Los padres de él',
    'Sr.y Sra.Smith',
    'Men in Black',
    'Naúfrago',
    'Sra.Doubtfire',
    'La momia',
    'Batman',
    'Rain Man',
    'El guardaespaldas',
    'Señales',
    'Madagascar',
    'Lo que el viento se llevó',
    'Robin Hood',
    'Superman',
    'Grease',
    'Happy Feet',
    'La Bella y la Bestia',
    'Ice Age',
    'Godzilla',
    '¿En qué piensan las mujeres?',
    'El fugitivo',
    'Hitch',
    'Jungla de cristal',
    'Notting Hill',
    'Algo pasa con Mary',
    'El planeta de los simios',
    'Los picapiedra',
    'Toy Story',
    'Minority Report',
    'Bichos',
    'El exorcista',
    'Mi gran boda griega',
    'Instinto Básico',
    'Regreso al futuro',
    'Se7en',
    '¿Quién engaño a Rogger Rabbit?',
    'Pocahontas',
    'Ratatouille',
    'Yo, Robot',
    'El Grinch',
    'Atrápame si puedes',
    'American Beauty',
    'Los 4 fantásticos',
    'Hora punta',
    'Cocodrilo Dundee',
    'El jorobado de Notre Dame',
    'El diablo viste de Prada',
    'La lista de Schindler',
    'La máscara',
    'Arma letal',
    'Superdetective en Hollywood',
    'Mejor imposible',
    'Una mente maravillosa',
    'Austin Powers',
    'Novia a la fuga',
    'Chicago',
    'Mentiroso compulsivo',
    'El espantatiburones',
    '101 Dálmatas',
    'Mulan',
    'Hook',
    'Rocky',
    'Rambo',
    'Chicken Little',
    'En busca de la felicidad',
    'Stuart Little',
    'Mira quien habla',
    'Los padres de ella',
    'Los cazafantasmas',
    'Doctor Dolittle',
    'Shakespeare in love',
    'El príncipe de Zamunda',
    'Speed',
    'Casper',
    'Infiltrados',
    'Lo que la verdad esconde',
    'El silencio de los corderos',
    'El profesor chiflado',
    'La milla verde',
    'Bambi',
    'XXX',
    'Jumanji',
    'El quinto elemento',
    'Lilo & Stitch',
    'Desafío total',
    'Borat',
    'Scary Movie',
    'Los ángeles de Charlie',
    'Full Monty',
    'El diario de Bridget Jones',
    'Lara Croft',
    'Hércules',
    'El show de Truman',
    'Babe',
    'El protegido',
    'Dos tontos muy tontos',
    'Robots',
    'Enemigo público',
    'El padrino',
    'Cuatro bodas y un funeral',
    '8 Millas',
    'Hulk',
    'Memorias de África',
    'Love Actually',
    'Fiebre del sábado noche',
    'Fast and Furious',
    'Un papá genial',
    'Las máscara del Zorro',
    'Bean',
    'El paciente inglés',
    'The Ring',
    'Inteligencia Artificial',
    'Constantine',
    'La vida es bella',
    'Hermano oso',
    'Space Jam',
    'Cariño, he encogido a los niños',
    'La Sirenita',
    'Ghost Rider',
    'El príncipe de Egipto',
    'La Terminal',
    'Wild Wild West',
    "mary poppins",
    'El patriota',
    'El caso Bourne',
    'Pulp Fiction',
    'Ace Ventura',
    'Miss Agente especial',
    'El libro de la selva',
    'Las tortugas ninja',
    'American Pie',
    "Titanic", 
	"Piratas del caribe", 
	"Avatar", 
	"Forrest gump", 
	"El señor de los anillos", 
	"Parque jurasico", 
	"Ironman", 
	"El exorcista", 	
	"Saw", 
	"King Kong", 
	"El padrino",
	"El sexto sentido", 
	"Pretty woman", 
	"Matrix", 
	"Braveheart", 
	"Pesadilla en Elm Street", 
	"Cadena perpetua", 
	"Independence Day (Dia de la independencia)", 
	"Psicosis", 
	"El resplandor", 
	"Pulp fiction", 
	"Los otros", 
	"Bailando con lobos", 
    "alien",
    "Scream",
    "Amelie",
    "El club de la lucha",
    "up",
    "Wall-e",
    "El hombre bicentenario",
    "tres metros sobre el cielo",
    "Blancanieves y los 7 enanitos",
    'Blade',
    "Dejavu",
    "Dentro del laberinto",
    "gremlins",
    "La historia interminable",
    "Los Goonies",
    "Colega, ¿dónde está mi coche?",
    "Drácula",
    "frankenstein",
    "El Bar Coyote",
    "El Ilusionista",
    "El laberinto del fauno",
    "El niño con el pijama de rayas",
    "El otro lado de la cama",
    "El perfume",
    "El pianista",
    "Kill Bill",
    'La bruja novata',
    "La dama y el vagabundo",
    "La liga de los hombres extraordinarios",
    "La naranja mecánica",
    "La pantera rosa",
    "la playa",
    "La vida de Bryan",
    "Soy Leyenda",
    "Taxi driver",
    "Torrente",
    "los juegos del hambre",
    "crepúsculo",
    "cenicienta",
    "Eduardo manostijeras",
    "Conan el Barbaro",
    "Resident evil",
    "Lo imposible",
    "Intocable",
    "Power rangers",
    "Mars attack",
    "Celda 211",
    "Pinocho",
    "El mago de Oz",
    "Sonrisas y Lágrimas",
    "Moulin Rouge",
    "Dirty Dancing",
    "Brokeback Mountain",
    "Friends",
    "Juego de Tronos",
    "Perdidos",
    "Expediente-X",
    "Los Simpsons",
    "Star Trek",
    "Dragon Ball",
    "Urgencias",
    "Breaking Bad",
    "Sexo en Nueva York",
    "Los Picapiedra",
    "Futurama",
    "Naufrago",
    "Acero Puro",
    "Los increibles",
    "Camino a la perdición",
    "Ocho apellidos vascos",
    "One punch man",
    "Death Note",
    "Salvar al soldado Ryan",
    "El efecto mariposa",
    "Spotlight",
    "Monstruos S.A.",
    "Deadpool",
    "Matrix",
    "Salvar al soldado Ryan",
    "Enemigo a las puertas",
    "Stranger things",
    "Los 100",
    "Indiana Jones",
    "Transporter",
    "Interstellar",
    "Tomb Raider",
    "El lado bueno de las cosas",
    "La bruja novata",
    "La familia adams",
    "Naufrago",
    "La gran evasión",
    "Lo imposible",
    "La isla", 
    "los vengadores",
    "Big",
    "El lago azul",
    "Ben hur",
    "El coleccionista de huesos",
    "Esta casa es una ruina",
    "El diario de noah",
    "Destino final",
    "Poltergeist",
    "Bob esponja",
    'Blade Runner',
    'Casablanca',
    '2001: Odisea del espacio',
    'Origen (Inception)',
    'Frozen',
    'La princesa prometida',
    'Bitelchús',
    'Mi chica',
    'Seven',
    'Juno',
    'El Cisne Negro',
    'Thor',
    'Mar adentro',
    'Ghost. Más allá del amor',
    'Slumdog Millionaire',
    'Shakespeare in love (Shakespeare enamorado)',
    'Todo sobre mi madre', 
    'Tesis',
    'Los lunes al sol', 
    'La isla minima',
    'REC',
    'El bola',
    'Peter pan',
    'Campeones',
    'Abre los ojos',
    'El día de la bestia',
    'Requiem por un sueño',
    'Apocalypse Now',
    'El bosque',
    'Memorias de África',
    'Vicky Cristina Barcelona',
    'Leyendas de pasión',
    'Ciudad de Dios',
    'La cosa',
    'La mosca',
    'Los Minions',
    'Gru, mi villano favorito',
    'Capitan America',
    'Guardianes de la Galaxia',
    'Inside Out (del reves)',
    'Wonder Woman',
    '2012',
    'Maléfica',
    'Escuadrón Suicida',
    'Gravity',
    'Doctor Strange',
    'Hercules',
    'Mandalorian',
    'Alicia en el país de las maravillas',
    'Big Hero 6',
    'Cube',
    "Enredados (Tangled)",
    'Rompe Ralph',
    'Cómo entrenar a tu dragón',
    'La llegada',
    'Westworld',
    'Marte',
    'Mad Max',
    'Anastasia',
    'CSI',
    'Bones',
    'Farmacia de guardia',
    'Compañeros',
    'Medico de familia',
    'Fisica o quimica',
    'Modern family',
    'The Walking Dead',
    'Heroes',
    'House',
    'American History X',
    'Cómo conocí a vuestra madre',
    'The Big Bang Theory',
    'El príncipe de Bel-Air',
    '7 Vidas',
    'Padre de familia',
    'Prison Break',
    'South Park',
    'Los vigilantes de la playa',
    'Aída',
    'Aquí no hay quien viva',
    'Dos hombres y medio',
    'Million Dollar Baby',
    'Los gemelos golpean dos veces',
    'Hot Shots!',
    'Loca academia de policía',
    'Heidi',
    'Hotel Transilvania',
    'Phenomenon',
    'Escuadrón suicida',
    '¿Conoces a Joe Black?',
    'Cantando bajo la lluvia',
    'Gattaca',
    'V de Vendetta',
    'Memento',
    'El club de los poetas muertos',
    'El lobo de Wall Street',
    'El renacido',
    'Shutter Island',
    'Django',
    'Diamante de sangre',
    'El hombre de la máscara de hierro',
    'Joker',
    'Fargo',
    'Chernobil',
    'Watchmen',
    'Vikingos',
    'Cristal Oscuro',
    'Narcos',
    'Spartacus',
    'Daredevil',
    'The Witcher',
    'Rick y Morty',
    'Lucifer',
    'Por trece razones',
    'La casa de papel',
    'Orange Is the New Black',
    'Sex Education',
    'Élite',
    'Peaky Blinders',
    'Sherlock',
    'Black Mirror',
    'BoJack Horseman',
    'Paquita Salas',
    'Shameless',
    'House of Cards',
    'The Crown'
];

