
window.songs = [
    'Cacho a cacho (Estopa)',
    "Hijo de la luna (Mecano)",
    "A Dios le pido (Juanes)",
    "No me doy por vencido (Luis Fonsi)",
    "Y nos dieron las diez (Joaquín Sabina)",
    "Corazón partío (Alejandro Sanz)",
    "Sin miedo a nada (Álex Ubago &amp; Amaia Montero)",
    "Entre dos tierras (Héroes Del Silencio)",
    "Mediterráneo (Joan Manuel Serrat)",
    "Libre (Nino Bravo)",
    "Lobo hombre en París (La Unión)",
    "19 días y 500 noches (Joaquín Sabina)",
    "La flaca (Jarabe De Palo)",
    "Ciega, sordomuda (Shakira)",
    "Me cuesta tanto olvidarte (Mecano)",
    "Ojalá que llueva café (Juan Luis Guerra y 4.40)",
    "Maldito duende (Héroes Del Silencio)",
    "A quién le importa (Alaska y Dinarama)",
    "Chica de ayer (Nacha Pop)",
    "Bulevar de los sueños rotos (Joaquín Sabina)",
    "Se fué (Laura Pausini)",
    "Ni tú ni nadie (Alaska y Dinarama)",
    "Sobreviviré (Mónica Naranjo)",
    "Como Camarón (Estopa)",
    "Héroe de leyenda (Héroes Del Silencio)",
    "Mujer contra mujer (Mecano)",
    "Livin' la vida loca (Ricky Martin)",
    "Déjame (Los Secretos)",
    "Sin ti no soy nada (Amaral)",
    "Cuéntame un cuento (Celtas Cortos)",
    "Siete vidas (Antonio Flores)",
    "París (La Oreja De Van Gogh)",
    "Es por ti (Cómplices)",
    "Cien gaviotas (Duncan Dhu)",
    "Santa Lucía (Miguel Ríos)",
    "Sólo le pido a Dios (Ana Belén)",
    "El sitio de mi recreo (Antonio Vega)",
    "Lucía (Joan Manuel Serrat)",
    "Insurrección (El Último De La Fila)",
    "Escuela de calor (Radio Futura)",
    "Sabor de amor (Danza Invisible)",
    "Bailar pegados (Sergio Dalma)",
    "Infinito (Bunbury)",
    "Devuélveme la vida (Antonio Orozco &amp; Malú)",
    "Aquí no hay playa (The Refrescos)",
    "Aquellas pequeñas cosas (Joan Manuel Serrat)",
    "Alicia (expulsada al país de las maravillas) (Bunbury)",
    "Esos locos bajitos (Joan Manuel Serrat)",
    "Aprendiz (Malú)",
    "Contamíname (Ana Belén y Víctor Manuel)",
    "Como hemos cambiado (Presuntos Implicados)",
    "Si tú no vuelves (Miguel Bosé)",
    "Una rosa es una rosa (Mecano)",
    "Asturias (Víctor Manuel)",
    "Aire (Mecano)",
    "Cuatro rosas (Gabinete Caligari)",
    "Lía (Ana Belén)",
    "No es lo mismo (Alejandro Sanz)",
    "El roce de tu piel (Revólver)",
    "Cuando el mar te tenga (El Último De La Fila)",
    "Voy en un coche (Christina y Los Subterráneos)",
    "Mi hogar en cualquier sitio (Antonio Vega)",
    "El lado oscuro (Jarabe De Palo)",
    "A fuego lento (Rosana)",
    "Barco a Venus (Mecano)",
    "Fueron los celos (La Unión)",
    "Años 80 (Los Piratas)",
    "Mucho mejor (Los Rodríguez)",
    "Moriría por vos (Amaral)",
    "No me importa nada (Luz)",
    "Duende (Miguel Bosé)",
    "Mi tierra (Gloria Estefan)",
    "Manos al aire (Nelly Furtado)",
    "Que nadie (Manuel Carrasco y Malú)",
    "Adoro (Armando Manzanero)",
    "Tú sigue así (OBK)",
    "Entre mis recuerdos (Luz)",
    "El talismán (Rosana)",
    "Abril (Antonio Flores)",
    "¿Lo ves? (Alejandro Sanz)",
    "Kamikaze (Amaral)",
    "¡Qué bonito! (Rosario)",
    "Tu calorro (Estopa)",
    "Silencio (David Bisbal)",
    "Como quieres que te quiera (Rosario)",
    "Un nuevo día brillará (Luz)",
    "Rozando la eternidad (Duncan Dhu)",
    "Besaré el suelo (Luz)",
    "Debajo del puente (Pedro Guerra)",
    "Ella (Bebe)",
    "Daniela (Pedro Guerra)",
    "No estamos lokos (Ketama)",
    "Ahí estás tú (Chambao)",
    "Siempre me quedará (Bebe)",
    "Alegría de vivir (Ray Heredia)",
    "Manuel, Raquel (Tam Tam Go!)",
    "Alma de blues (Presuntos Implicados)",
    "Mi pequeño tesoro (Presuntos Implicados)",
    "Aburrido de esperar (Marc Parrot)",
    "Nadie como tú (Presuntos Implicados &amp; Francisco Céspedes)",
    "Agua y sal (Rosario)",

    "Michael Jackson (Thriller)",
    "Imagine (John Lennon)",
    "Waka Waka (Shakira)",
    "Titanic (Celine Dion)",
    "Gangnam style (Psy)",
    "Bohemian Rhapsody (Queen)",
    "One Direction (What Makes You Beautiful)",
    "Party in the U.S.A (Miley Cyrus)",
    "The Beatles (Hey Jude)",
    "Rihanna Diamonds)",
    "Bad Romance (Lady gaga)",
    "Baby (Justin Bieber)",
    "Miley Cyrus (The Climb)",
    "Poker Face Lady Gaga)",
    "We Can't Stop (Miley Cyrus)",
    "Baby One More Time (Britney Spears)",
    "Michel telo (Ai Se Eu Te Pego)",
    "Katy Perry (The One That Got Away)",
    "Taylor Swift (I Knew You Were Trouble)",
    "Toxic (Britney Spears)",
    "The Rolling Stones (Doom And Gloom)",
    "Beyoncé (Run the World (Girls))",
    "Nicki Minaj (Super Bass)",
    "Music (Madonna)"
];

